### ISSUE TITLE
Reference to unset environment variable QML_CLIENT_PORT

### ISSUE THREAD

**Issue by jedfrechette** [pyblish/developer-guide#3]
developing_with_ipc.md refers to the environment variable QML_CLIENT_PORT. The currently released windows installer (1.2.4) doesn't set this variable. Grepping through the current master branch of pyblish-x also doesn't turn up any reference to this variable.

**Comment by mottosso** [comment]
Thanks for reporting this. This was a typo, the correct name is `PYBLISH_CLIENT_PORT`. Fixed.
